config/routes.rb
Rails.application.routes.draw do
  resources :tracks

  get 'pages/home' => 'pages#home'

  get 'pages/about' =>'pages#about'

  get 'broadcasts/timeline' =>'broadcasts#timeline'

  resources :broadcasts
  
  root 'broadcasts#index'
end

app/models/broadcast.rb
class Broadcast < ActiveRecord::Base
	def self.get_latest
		self.order("broadcast_date DESC").first
	end

	#validates :url, :presence => true
end

app/models/track.rb
class Track < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/broadcasts_controller.rb
class BroadcastsController < ApplicationController
	before_action :set_broadcast, only: [:show, :edit]
	caches_page :index

	def index
		@broadcastsFirst = Broadcast.all.order(broadcast_date: :desc).first
		@broadcastsLast = Broadcast.all.order(broadcast_date: :desc).last
	end

	def show
	end

	def timeline
	  @broadcasts = Broadcast.all.order(broadcast_date: :desc).to_json
	end

	private
    # Use callbacks to share common setup or constraints between actions.
    def set_broadcast
      @broadcast = Broadcast.find params[:id]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@mix = Broadcast.get_latest
  end

  def about
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to @track, notice: 'Track was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tracks/1
  def update
    if @track.update(track_params)
      redirect_to @track, notice: 'Track was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tracks/1
  def destroy
    @track.destroy
    redirect_to tracks_url, notice: 'Track was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def track_params
      params[:track]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/broadcasts/_form.html.erb
<%= simple_form_for(@broadcast) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :broadcast_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/broadcasts/edit.html.erb
<h1>Editing Broadcast</h1>

<%= render 'form' %>

<%= link_to 'Show', @broadcast %> |
<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/index.html.erb
<nav>
	<p id="home"><img src="<%= asset_url 'icons/list.svg' %>"></p>
	<p id="search"><img src="<%= asset_url 'icons/magnifying-glass.svg' %>"></p>
	<p id="playing">
		<img id="playButton" src="<%= asset_url 'icons/bar-graph.svg' %>">
		<img id="pauseButton" src="<%= asset_url 'icons/pause.svg' %>">
	</p>
</nav>

<div id="playDetails">
	<p>27-12-13<br />Bonobo, DK, Coldcut, DJ Cheeba, DJ Food, DJ Moneyshot, Hexstatic</p>	
</div>



<div id="container">
	<div id="inner-container">

		<div id="timeline" class="push">
			<!-- 2010s -->
			<div class="decade current-decade">
				<div class="year">2015</div>
				<div class="year">14</div>
				<div class="year">13</div>
				<div class="year">12</div>
				<div class="year">11</div>
				<div class="year"><span class="showWhenBig">20</span>10</div>
			</div>

			<!-- 00s -->
			<div class="decade">
				<div class="year"><span class="hideWhenSmall">20</span>09</div>
				<div class="year">08</div>
				<div class="year">07</div>
				<div class="year">06</div>
				<div class="year">05</div>
				<div class="year">04</div>
				<div class="year">03</div>
				<div class="year">02</div>
				<div class="year">01</div>
				<div class="year">2000</div>
			</div>

			<!-- 90s -->
			<div class="decade">
				<div class="year"><span class="hideWhenSmall">19</span>99</div>
				<div class="year">98</div>
				<div class="year">97</div>
				<div class="year">96</div>
				<div class="year">95</div>
				<div class="year">94</div>
				<div class="year">93</div>
				<div class="year">92</div>
				<div class="year">91</div>
				<div class="year">1990</div>
			</div>

			<!-- earlier/other -->
			<div class="decade">
				<div class="year">1989</div>
				<div class="year">1988</div>
			</div>
		</div>

		<div id="play" class="play firstPlay" style="display:none">
			
		</div>

		<div id="search-form" style="display:none">
			<form>
				<input type="text" placeholder="Search by artist, track, date" />
				<span></span>
			</form>
		</div>

		<div id="search-timeline" class="push">
			<!-- 2010s -->
			<div class="decade current-decade">
				<div class="year">2015</div>
				<div class="year">14</div>
				<div class="year current">13</div>
				<div class="year current">12</div>
				<div class="year current">11</div>
				<div class="year">2010</div>

			</div>

			<!-- 00s -->
			<div class="decade">
				<div class="year"><span class="hideWhenSmall">20</span>09</div>
				<div class="year current">08</div>
				<div class="year">07</div>
				<div class="year">06</div>
				<div class="year">5</div>
				<div class="year">04</div>
				<div class="year">03</div>
				<div class="year">02</div>
				<div class="year">01</div>
				<div class="year">2000</div>
			</div>

			<!-- 90s -->
			<div class="decade">
				<div class="year"><span class="hideWhenSmall">19</span>99</div>
				<div class="year">8</div>
				<div class="year">7</div>
				<div class="year">6</div>
				<div class="year">5</div>
				<div class="year">4</div>
				<div class="year">3</div>
				<div class="year">2</div>
				<div class="year">1</div>
				<div class="year">1990</div>
			</div>

			<!-- earlier/other -->
			<div class="decade">
				<div class="year">1988</div>
				<div class="year">1989</div>
			</div>
		</div>

		<div id="menu" class="panel" role="navigation">
			<h3>2013</h3>
			<div>
				<p>DEC</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolpariatur.</a></p>
			</div>
			<div>
				<p>NOV</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
					tempor incididunt ut labo at laborum.</a></p>
				</a>
			</div>
			<div>
				<p>OCT</p>
				<p><a href="#" onclick="play()">Sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>SEP</p>
				<p><a href="#" onclick="play()">Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>AUG</p>
				<p><a href="#" onclick="play()">oluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>JUL</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amet, iatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>JUN</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amet, consectetur adipisicuptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>MAY</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor son ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>APR</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitfficia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>MAR</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation lla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>FEB</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor tion ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
			<div>
				<p>JAN</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor ion ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute iruulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</a></p>
			</div>
		</div>





		<div id="search-menu" class="panel" role="navigation">
			<h3>Search results for <b>"bonobo"</b></h3>
			<div>
				<p style="text-decoration:underline">2013</p>
				<p>DEC</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amco laboris nisi ut olor sit amco laboris nisi ut</a></p>
				<br />
			</div>
			<div>
				<p style="text-decoration:underline">2012</p>
				<p>JUN</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amco laboris nisi ut olor sit amco laboris nisi ut</a></p>
				<br />
			</div>
			<div>
				<p style="text-decoration:underline">2011</p>
				<p>OCT</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amco laboris nisi ut olor sit amco laboris nisi ut enderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</a></p>
				<p>JUN</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amco laboris nisi ut olor sit amco laboris nisi ut</a></p>
				<br />
			</div>
			<div>
				<p style="text-decoration:underline">2008</p>
				<p>MAR</p>
				<p><a href="#" onclick="play()">Lorem ipsum dolor sit amco laboris nisi ut olor sit amco laboris nisi ut enderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</a></p>
				<br />
			</div>
		</div>
	</div>
</div>
<nav id="social">
	<p id="fb"><a href="#">facebook</a></p>
	<p id="tw"><a href="#">twitter</a></p>
	<p id="vm"><a href="#">vimeo</a></p>
	</nav>

app/views/broadcasts/new.html.erb
<h1>New Broadcast</h1>

<%= render 'form' %>

<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @broadcast.broadcast_date %></p>
<p><%= @broadcast.session_name %></p>
<p><%= @broadcast.part1title %></p>
<p><%= @broadcast.part2title %></p>
<p><%= @broadcast.part3title %></p>
<p><%= @broadcast.part4title %></p>
<p><%= @broadcast.ra1 %></p>
<p><%= @broadcast.ra2 %></p>
<p><%= @broadcast.ra3 %></p>

<%= link_to 'Back', broadcasts_path %>

app/views/broadcasts/timeline.html.erb
<div id="tl" style="height: 400px; width: 100%; margin-top: 50px;"></div>
<div style="width: 80%; margin: 20px auto; font-size: 24px;">
	<input style="float: left;" type="button" value="Move year left" title="Move year left" onclick="animateTo('back', 'year');">
	<input style="float: left;" type="button" value="Move month left" title="Move month left" onclick="animateTo('back', 'month');">
	<input style="float: right;" type="button" value="Move year right" title="Move right" onclick="animateTo('forward', 'year');">
	<input style="float: right;" type="button" value="Move month right" title="Move right" onclick="animateTo('forward', 'month');">
</div>
<div id="tl2" style="height: 400px; width: 100%; margin-top: 20px;"></div>

<script>
/* inject json into page */
var broadcasts = <%= @broadcasts.to_s.html_safe %>;


/* navigate the timeline */
function move(moveVal) {
    timeline.move(moveVal);
    timeline.trigger("rangechange");
    timeline.trigger("rangechanged");
}


/* animate back/forward one page */
var animateTimeout = undefined;
var animateFinal = undefined;

function animateTo(direction, scale) {

	var range = (scale == 'month' ? timeline1.getVisibleChartRange() : timeline2.getVisibleChartRange());

	if (direction == "forward") {
		animateFinal = range.end.getTime();
	} else { /* back */
		animateFinal = range.start.getTime();
	}
	
	scale == 'month' ? timeline1.setCustomTime(animateFinal) : timeline2.setCustomTime(animateFinal);

	// cancel any running animation
	animateCancel();

	// animate towards the final date
	var animate = function () {
		var range = (scale == 'month' ? timeline1.getVisibleChartRange() : timeline2.getVisibleChartRange());
		var current = (range.start.getTime() + range.end.getTime())/ 2;
		var width = (range.end.getTime() - range.start.getTime());
	    var minDiff = Math.max(width / 1000, 1);
		var diff = (animateFinal - current);
	    if (Math.abs(diff) > minDiff) {
	        // move towards the final date
	        var start = new Date(range.start.getTime() + diff / 3);
	        var end = new Date(range.end.getTime() + diff / 3);
	        
	        scale == 'month' ? timeline1.setVisibleChartRange(start, end) : timeline2.setVisibleChartRange(start, end);

	        // start next timer
	        animateTimeout = setTimeout(animate, 50);
	    }
	    scale == 'month' ? timeline1.trigger('rangechange') : timeline2.trigger('rangechange');
	};
	animate();
}

function animateCancel () {
    if (animateTimeout) {
        clearTimeout(animateTimeout);
        animateTimeout = undefined;
    }
}


/* format the data for timeline use */
var data = [];

for(i = 0; i < broadcasts.length; i++) {
  data.push({
  'start': new Date(broadcasts[i].broadcast_date),
  'content' : "<a href='/broadcasts/"+broadcasts[i].id+"'>" + broadcasts[i].session_name + "</a>"
  });
}


/* functions to keep timelines in sync */
function onrangechange1() {
    var range = timeline1.getVisibleChartRange();
    timeline2.setVisibleChartRange(range.start, range.end);
}

function onrangechange2() {
    var range = timeline2.getVisibleChartRange();
    timeline1.setVisibleChartRange(range.start, range.end);
}


/* instantiate the timeline (month scale) */
var timeline1 = new links.Timeline(document.getElementById('tl'));

/* add event listener */
links.events.addListener(timeline1, 'rangechange', onrangechange1);

/* draw the first timeline */
timeline1.draw(data, { zoomMax : 2419200000, zoomMin : 2419200000, height: "100%", min: new Date("1 July 1998")});

/* instantiate 2nd timeline (year scale) */
var timeline2 = new links.Timeline(document.getElementById('tl2'));

/* add event listener */
links.events.addListener(timeline2, 'rangechange', onrangechange2);

timeline2.draw(data, { zoomMax : 31536000000, zoomMin : 31536000000, height: "100%", min: new Date("1 July 1998"), 'style': 'dot'});

onrangechange1();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <title><%= title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>" style="background-image:url(<%= asset_url 'backgrounds/bonobo.jpg' %>); background-size: cover; background-position: 50% 50%; background-repeat: no-repeat">
  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>

  <script type="text/javascript">
    (function() {
        var path = '//easy.myfonts.net/v2/js?sid=267599(font-family=Decima+Pro+Light)&sid=267601(font-family=Decima+Pro)&sid=267602(font-family=Decima+Pro+Bold)&key=wQmdUZ5j9v',
            protocol = ('https:' == document.location.protocol ? 'https:' : 'http:'),
            trial = document.createElement('script');
        trial.type = 'text/javascript';
        trial.async = true;
        trial.src = protocol + path;
        var head = document.getElementsByTagName("head")[0];
        head.appendChild(trial);
    })();
</script>

<script type="text/javascript">
    (function() {
        var path = '//easy.myfonts.net/v2/js?sid=255331(font-family=Decima+Mono+X+Bold)&sid=255332(font-family=Decima+Mono+X+Light)&sid=255335(font-family=Decima+Mono+X)&key=EGiDn8fIsE',
            protocol = ('https:' == document.location.protocol ? 'https:' : 'http:'),
            trial = document.createElement('script');
        trial.type = 'text/javascript';
        trial.async = true;
        trial.src = protocol + path;
        var head = document.getElementsByTagName("head")[0];
        head.appendChild(trial);
    })();
</script>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<p>this is the homepage.</p>

<p>here is the latest mix:</p>
<div class="latest-mix">
	<iframe id="track" width="100%" height="166" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%= @mix.url %>&color=0066cc"></iframe>
</div>

<p><a href="/broadcasts">Broadcasts</a></p>
<p><a href="/tracks">Tracks</a></p>

app/views/tracks/_form.html.erb
<%= simple_form_for(@track) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tracks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= link_to "#{track.artist} /  #{track.title}", track unless track.artist.nil? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p><a href="/broadcasts/<%= @track.broadcast_id %>">broadcast <%= @track.broadcast_id %></a></p>
<p><%= @track.part %></p>
<p><%= @track.artist %></p>
<p><%= @track.title %></p>
<p><%= @track.composed %></p>
<p><%= @track.published %></p>
<p><%= @track.record_label %></p>
<p><%= @track.catalogue_no %></p>
<p><%= @track.duration %></p>
<p><%= @track.notes %></p>

<%= link_to 'Back', tracks_path %>